# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 01:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('AnnouncementId', models.AutoField(primary_key=True, serialize=False)),
                ('OutputText', models.TextField(max_length=8192)),
                ('Comments', models.CharField(max_length=1024, null=True)),
                ('CreatedOn', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Created On')),
                ('ExpireOn', models.DateField(default=datetime.datetime.now, verbose_name=b'Expire On')),
            ],
        ),
        migrations.CreateModel(
            name='positionJSONHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ICAO', models.CharField(max_length=8, null=True)),
                ('Flight', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Created On')),
                ('altitude', models.IntegerField(default=0, null=True)),
                ('latitude', models.FloatField(default=0, null=True)),
                ('longititude', models.FloatField(max_length=8, null=True)),
                ('squawk', models.CharField(max_length=10, null=True)),
                ('nucp', models.IntegerField(default=0, null=True)),
                ('seen_pos', models.FloatField(max_length=8, null=True)),
                ('vert_rate', models.IntegerField(default=0, null=True)),
                ('track', models.IntegerField(default=0, null=True)),
                ('speed', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(max_length=6, null=True)),
                ('messages', models.IntegerField(default=0, null=True)),
                ('seen', models.FloatField(max_length=8, null=True)),
                ('rssi', models.FloatField(max_length=8, null=True)),
            ],
        ),
    ]
