package com.svcvllc.test12c.model.View;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 23 23:41:45 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SnippetVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SnippetVOImpl() {
    }
}

