package com.svcvllc.test12c.model.Entity;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 21 23:44:52 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuthUserEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        Password,
        LastLogin,
        IsSuperuser,
        Username,
        FirstName,
        LastName,
        Email,
        IsStaff,
        IsActive,
        DateJoined;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int PASSWORD = AttributesEnum.Password.index();
    public static final int LASTLOGIN = AttributesEnum.LastLogin.index();
    public static final int ISSUPERUSER = AttributesEnum.IsSuperuser.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ISSTAFF = AttributesEnum.IsStaff.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int DATEJOINED = AttributesEnum.DateJoined.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AuthUserEOImpl() {
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.svcvllc.test12c.model.Entity.AuthUserEO");
    }


}

