package com.svcvllc.test12c.model.Entity;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 21 23:20:13 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SnippetEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        Created,
        Title,
        Code,
        Linenos,
        Language,
        Style,
        Highlighted,
        OwnerId;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return SnippetEOImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return SnippetEOImpl.AttributesEnum.firstIndex() + SnippetEOImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = SnippetEOImpl.AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int ID = AttributesEnum.Id.index();
    public static final int CREATED = AttributesEnum.Created.index();
    public static final int TITLE = AttributesEnum.Title.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int LINENOS = AttributesEnum.Linenos.index();
    public static final int LANGUAGE = AttributesEnum.Language.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int HIGHLIGHTED = AttributesEnum.Highlighted.index();
    public static final int OWNERID = AttributesEnum.OwnerId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SnippetEOImpl() {
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.svcvllc.test12c.model.Entity.SnippetEO");
    }


}

