package com.svcvllc.test12c.model.service;

import com.svcvllc.test12c.model.View.SnippetVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 23 23:33:20 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RestAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RestAppModuleImpl() {
    }

    /**
     * Container's getter for SnippetVO1.
     * @return SnippetVO1
     */
    public SnippetVOImpl getSnippetVO1() {
        return (SnippetVOImpl)findViewObject("SnippetVO1");
    }

    /**
     * Container's getter for AuthUserVO1.
     * @return AuthUserVO1
     */
    public ViewObjectImpl getAuthUserVO1() {
        return (ViewObjectImpl)findViewObject("AuthUserVO1");
    }

    /**
     * Container's getter for SnippetVO2.
     * @return SnippetVO2
     */
    public SnippetVOImpl getSnippetVO2() {
        return (SnippetVOImpl)findViewObject("SnippetVO2");
    }

    /**
     * Container's getter for User2SnippetsvL1.
     * @return User2SnippetsvL1
     */
    public ViewLinkImpl getUser2SnippetsvL1() {
        return (ViewLinkImpl)findViewLink("User2SnippetsvL1");
    }
}

